"use client";

import React, { useState, useEffect } from "react";
import { DecisionRecord } from "@/lib/types";
import {
  ShieldCheckIcon,
  PlayIcon,
  CheckIcon,
  XIcon,
  ArrowRightIcon,
  BugIcon,
  SparklesIcon,
} from "./icons";

interface DemoTourModalProps {
  isOpen: boolean;
  onClose: () => void;
  decision: DecisionRecord | null;
  onSelectTab: (tab: "overview" | "investigations" | "evidence" | "verify" | "tamper") => void;
  onTriggerVerify: () => Promise<void>;
  onTriggerTamper: () => Promise<void>;
}

interface TourStep {
  title: string;
  subtitle: string;
  tab: "overview" | "investigations" | "evidence" | "verify" | "tamper";
  instruction: string;
  bulletPoints: string[];
  actionLabel?: string;
}

const TOUR_STEPS: TourStep[] = [
  {
    title: "Step 1 · AI Decision Captured",
    subtitle: "Select Case A-4821 in the Investigation Dashboard",
    tab: "overview",
    instruction: "A disputed AI credit scoring decision for applicant A-4821 has been recorded through CooL.",
    bulletPoints: [
      "Application: A-4821 (Borrower: Jordan Vance)",
      "Model: acme/credit-scorer (v2026.06.0)",
      "Outcome: APPROVED ($12,000)",
      "CooL SDK generated a tamper-evident receipt with salted commitments",
    ],
    actionLabel: "Open Case Investigation",
  },
  {
    title: "Step 2 · Investigate Causality & Timeline",
    subtitle: "Examine Model Execution to Receipt Generation",
    tab: "investigations",
    instruction: "Explore the chronological timeline reconstructing the entire lifecycle of the decision.",
    bulletPoints: [
      "Model inference evaluated against lending-policy-v4 rules",
      "Underwriter outcome: TIER_1_PRIME at 6.5% interest rate",
      "Event core sealed with monotonic ULID sequence and timestamp",
      "Evidence commitments prepared without leaking raw financial data",
    ],
    actionLabel: "Inspect Evidence Receipt",
  },
  {
    title: "Step 3 · Cryptographic Receipt & Privacy",
    subtitle: "Salted Commitments & Hybrid Post-Quantum Keys",
    tab: "evidence",
    instruction: "Verify that zero applicant PII or credit scores leak into the receipt wire format.",
    bulletPoints: [
      "Binding Hash: Canonical CBOR SHA-256 multihash",
      "Signature Suite: ML-DSA-65 (FIPS 204) + Ed25519",
      "Transparency Log: RFC 6962 Merkle tree insertion with audit path",
      "Runtime: Honestly reports 'Simulated TDX' (never fake hardware attestation)",
    ],
    actionLabel: "Proceed to Verification Center",
  },
  {
    title: "Step 4 · Real Verification Execution",
    subtitle: "Execute Standalone 7-Domain Verifier",
    tab: "verify",
    instruction: "Call POST /api/verify to independently test the clean evidence offline.",
    bulletPoints: [
      "Binding Check: PASS (digest matches core)",
      "Signature Check: PASS (hybrid post-quantum keys valid)",
      "Inclusion Check: PASS (Merkle audit path verified)",
      "Result: VERIFIED across all active domains",
    ],
    actionLabel: "Open Tamper Lab",
  },
  {
    title: "Step 5 · Simulate Adversarial Tampering",
    subtitle: "Mutate Cryptographic Fields in Tamper Lab",
    tab: "tamper",
    instruction: "Launch a metadata commitment attack flipping a character in event.metadata_hash.",
    bulletPoints: [
      "Simulates an attacker trying to alter the model version or policy after the fact",
      "Deep-clones real evidence and applies precise mutation",
      "Executes real verifyEvidence() on both original and forged copies",
      "Side-by-side comparison reveals immediate cryptographic failure",
    ],
    actionLabel: "Simulate Attack & Observe Breach",
  },
  {
    title: "Step 6 · Forensic Detection & Diagnostic",
    subtitle: "Mathematical Proof of Tampering",
    tab: "tamper",
    instruction: "Review the exact failure diagnostic reasons generated by CooL.",
    bulletPoints: [
      "Result: FAILED (Binding FAIL, Signature FAIL)",
      "Reason: 'binding_hash does not match the receipt'",
      "Reason: 'ML-DSA-65 and Ed25519 did not verify'",
      "Proves beyond doubt that the evidence was altered post-decision",
    ],
    actionLabel: "Finish Demo Tour",
  },
];

export function DemoTourModal({
  isOpen,
  onClose,
  decision,
  onSelectTab,
  onTriggerVerify,
  onTriggerTamper,
}: DemoTourModalProps) {
  const [currentStepIdx, setCurrentStepIdx] = useState(0);

  useEffect(() => {
    if (isOpen) {
      setCurrentStepIdx(0);
      onSelectTab(TOUR_STEPS[0].tab);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const currentStep = TOUR_STEPS[currentStepIdx];
  const isLast = currentStepIdx === TOUR_STEPS.length - 1;

  const handleNext = async () => {
    if (currentStepIdx === 3) {
      // At step 4 (index 3), trigger real verification
      await onTriggerVerify();
    } else if (currentStepIdx === 4) {
      // At step 5 (index 4), trigger real tampering
      await onTriggerTamper();
    }

    if (isLast) {
      onClose();
    } else {
      const nextIdx = currentStepIdx + 1;
      setCurrentStepIdx(nextIdx);
      onSelectTab(TOUR_STEPS[nextIdx].tab);
    }
  };

  const handlePrev = () => {
    if (currentStepIdx > 0) {
      const prevIdx = currentStepIdx - 1;
      setCurrentStepIdx(prevIdx);
      onSelectTab(TOUR_STEPS[prevIdx].tab);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-end sm:items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-xl w-full p-6 shadow-2xl space-y-5 font-mono text-xs animate-scaleIn">
        {/* Progress Bar & Header */}
        <div className="space-y-2">
          <div className="flex items-center justify-between text-[11px] text-slate-400">
            <span className="flex items-center gap-1.5 text-sky-400 font-bold">
              <PlayIcon className="w-3 h-3 fill-current text-sky-400" />
              <span>GUIDED DEMO TOUR</span>
            </span>
            <span>
              Step {currentStepIdx + 1} of {TOUR_STEPS.length}
            </span>
          </div>

          <div className="w-full bg-slate-950 h-1.5 rounded-full overflow-hidden border border-slate-800">
            <div
              className="bg-sky-500 h-full transition-all duration-300"
              style={{
                width: `${((currentStepIdx + 1) / TOUR_STEPS.length) * 100}%`,
              }}
            />
          </div>
        </div>

        {/* Step Content */}
        <div className="space-y-3">
          <div>
            <h3 className="text-base font-bold text-white tracking-tight">
              {currentStep.title}
            </h3>
            <div className="text-xs text-slate-400 mt-0.5">{currentStep.subtitle}</div>
          </div>

          <p className="text-xs text-slate-300 font-sans leading-relaxed">
            {currentStep.instruction}
          </p>

          <div className="p-3.5 bg-slate-950/80 rounded-lg border border-slate-800 space-y-1.5">
            {currentStep.bulletPoints.map((pt, i) => (
              <div key={i} className="flex items-start gap-2 text-[11px] text-slate-300">
                <span className="text-sky-400 font-bold">•</span>
                <span className="font-sans leading-relaxed">{pt}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Navigation Buttons */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-800">
          <button
            onClick={onClose}
            className="px-3 py-1.5 rounded text-slate-400 hover:text-white transition-colors"
          >
            Skip Tour
          </button>

          <div className="flex items-center gap-2">
            {currentStepIdx > 0 && (
              <button
                onClick={handlePrev}
                className="px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              >
                Back
              </button>
            )}

            <button
              onClick={handleNext}
              className="px-4 py-2 rounded bg-sky-600 hover:bg-sky-500 text-white font-bold transition-all flex items-center gap-1.5 shadow-lg shadow-sky-950/40"
            >
              <span>{currentStep.actionLabel || (isLast ? "Finish Tour" : "Next Step")}</span>
              <ArrowRightIcon className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
